---

- hosts: all
  become: true
  pre_tasks:

  - name: Atualiza Servidores Fedora
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Atualiza Servidores Ubuntu
    tags: always
    apt:
      update_cache: yes
      upgrade: safe
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Instala Apache em Servidores Fedora
    tags: apache,httpd,fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Instala Apache em Servidores Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: Instala Maria-DB em Servidores Fedora
    tags: fedora,maridadb,db
    dnf: 
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Instala Marida-DB em Servidores Ubuntu
    tags: ubuntu,mariadb,db
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Instala Samba em Servidores Fedora
    tags: samba,fedora
    dnf:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Instala Samba em Servidores Ubuntu
    tags: samba,ubuntu
    apt:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"
...
