---

- hosts: all
  become: true
  tasks:
  - name: instala updates em servidores fedora
    dnf:
      name:
        - update_only: yes
        - update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: instala updates em servidores ubuntu
    apt:
      name:
        - upgrade: dist
        - update_cache: yes
    when: ansible_distribution == "Ubuntu"

...
